export const FETCH_TRENDING_MOVIE_RESPONSE = "FETCH_TRENDING_MOVIE_RESPONSE"
export const FETCH_TRENDING_MOVIE_SUCCESS = "FETCH_TRENDING_MOVIE_SUCCESS"
export const FETCH_TRENDING_MOVIE_FAIL = "FETCH_TRENDING_MOVIE_FAIL"

export const SEARCH_QUERY = "SEARCH_QUERY"

export const FETCH_MOVIE_RESPONSE = "FETCH_MOVIE_RESPONSE"
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS"
export const FETCH_MOVIE_FAIL = "FETCH_MOVIE_FAIL"

// filter 
export const SET_FILTER = "SET_FILTER"
export const FILTER_MOVIES_RESPONSE = "FILTER_MOVIES_RESPONSE"
export const FILTER_MOVIES_SUCCESS = "FILTER_MOVIES_SUCCESS"
export const FILTER_MOVIES_FAIL = "FILTER_MOVIES_FAIL"


export const LOADMORE_MOVIE_RESPONSE = "LOADMORE_MOVIE_RESPONSE"
export const LOADMORE_MOVIE_SUCCESS = "LOADMORE_MOVIE_SUCCESS"
export const LOADMORE_MOVIE_FAIL = "LOADMORE_MOVIE_FAIL"
export const LOADMORE_MOVIE_ = "LOADMORE_MOVIE"



export const WATCH_TRAILER_RESPONSE = "WATCH_TRAILER_RESPONSE"
export const WATCH_TRAILER_SUCCESS = "WATCH_TRAILER_SUCCESS"
export const WATCH_TRAILER_FAIL = "WATCH_TRAILER_FAIL"


// get movie by id || get single movie
export const SINGLE_RESPONSE = "SINGLE_RESPONSE"
export const SINGLE_SUCCESS = "SINGLE_SUCCESS"
export const SINGLE_FAIL = "SINGLE_FAIL"

export const SINGLE_CAST_RESPONSE = "SINGLE_CAST_RESPONSE"
export const SINGLE_CAST_SUCCESS = "SINGLE_CAST_SUCCESS"
export const SINGLE_CAST_FAIL = "SINGLE_CAST_FAIL"

// similar
export const SIMILAR_RESPONSE = "SIMILAR_RESPONSE"
export const SIMILAR_SUCCESS = "SIMILAR_SUCCESS"
export const SIMILAR_FAIL = "SIMILAR_FAIL"


// Tv
export const FETCH_TV_RESPONSE = "FETCH_TV_RESPONSE"
export const FETCH_TV_SUCCESS = "FETCH_TV_SUCCESS"
export const FETCH_TV_FAIL = "FETCH_TV_FAIL"

export const LOADMORE_TV_RESPONSE = "LOADMORE_TV_RESPONSE"
export const LOADMORE_TV_SUCCESS = "LOADMORE_TV_SUCCESS"
export const LOADMORE_TV_FAIL = "LOADMORE_TV_FAIL"

// @DESC Episode 
export const EPISODE_RESPONSE = "EPISODE_RESPONSE"
export const EPISODE_SUCCESS = "EPISODE_SUCCESS"
export const EPISODE_FAIL = "EPISODE_FAIL"